[[bin]]
name="database"
path="database/src/main.rs"

[package]
name = "database"
version = "0.1.0"
authors = ["messenger <or.no.world@gmail.com>"]
edition = "2018"

[dependencies]
core = {path = "core"}
model = {path = "model"}